# For more information about the available options please visit: http://go/catalog-info (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: Unity-Technologies/unity-agent-plugin
    backstage.io/techdocs-ref: dir:.
  name: unity-agent-plugin
  description: "Unity plugin for third-party agent platforms"
  labels:
    costcenter: "5055"
  tags:
    - planned-public
    - enterprise
  links:
    - url: https://unity.slack.com/messages/C0BL0JUVA91/
      title: "#gaming-ai-thirdparty-plugins"
      icon: chat
spec:
  type: library
  lifecycle: production
  owner: Unity-Technologies/ai-assistant-devs
